application: Enter your app id
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: icon.png
  upload: favicon\.ico

- url: /assets
  static_dir: static/assets

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /*
  static_dir: static

libraries:
- name: webapp2
  version: "2.5.2"
